### PR TITLE
Feature/emailjs

### LINKED ISSUE #8: Contact us form need to be implemented with MailChimp
The Contact Us Form is not working. Its need to be configured with the Mail Chimp Service. 
The Mail should be addressed to **githubcommunitysl@gmail.com**

### PR DESCRIPTION
**Pull request by ebonynon**
fix #8 

- Add [EmailJs](https://www.emailjs.com/)
- Update SLIIT FOSS logo

### CODE REVIEW

**Review by Shehanka — APPROVED** [review]
@ebonynon Great work!

@Safnaj can you have a look and merge this

**Comment by Safnaj** [comment]
> @ebonynon Great work!
> 
> @Safnaj can you have a look and merge this

@ebonynon we should have create an account in emailjs and add the credentials here right ??

**Comment by ebonynon** [comment]
> @ebonynon we should have create an account in emailjs and add the credentials here right ??

That's up to you; if you okay with my current account you can use it or you can create your own one. 
Please check your email, I already sent testing emails.

**Review by Safnaj — APPROVED** [review]

**Review by Safnaj — APPROVED** [review]
Awesome

**Comment by Safnaj** [comment]
Thanks for letting us know Email.js

**Comment by Safnaj** [comment]
@ebonynon as i checked, we are not receiving username, user email or subject. Only the message being sent.
Also it would be great if we can reset the form after the submission and show a mail sent alert.

**Comment by ebonynon** [comment]
> @ebonynon as i checked, we are not receiving username, user email or subject. Only the message being sent.
> Also it would be great if we can reset the form after the submission and show a mail sent alert.

You can do it by creating a new email template

**Pull request merged**
